### ISSUE TITLE
Support for select2 4.0

### ISSUE THREAD

**Issue by ksikka** [LoicMahieu/select2-browserify#4]
The release candidate of select2 4.0 is out, any plans on supporting it? If so, I'd be glad to contribute.

**Comment by LoicMahieu** [comment]
For updating select2, just update git submodule and that sit. PR me and I will publish.

In fact I do not use this module anymore. Maybe I may encourage you to not use it. You can find workaround :
 - Be careful, NPM module `select2` is a copy of select2 ! And it is not up to date.
 - NPM can install via git or github: `npm install select2/select2` will install the official version
 - You can require select2 module by: `require('select2/select2')
 - select2 depends on jQuery so you had to export it to global:
```js
window.jQuery = require('jquery')
```
Or you can shim it with browserify-shim.

I found some issues related to this: https://github.com/select2/select2/search?q=browserify&type=Issues&utf8=%E2%9C%93
And someone made a "demo": https://github.com/pagenoare/select2-browserify-example

I hope I help you. I close the issue, don't hesitate to continue discussion here.

**Comment by hailwood** [comment]
Hi @LoicMahieu 

Are you able to share a working example with browserify-shim and version 4.0.0? I cannot seem to get it work no matter what I do.

I tried following the demo above and it didn't work either.

**Comment by bluespore** [comment]
@hailwood I've just spent a bit of time dealing with the same issue. I got it working by using `window.jQuery = $ = require('jquery');`

Using jQuery 1.11.3 from npm, using the Select2 package as indicated by @LoicMahieu above.

Can confirm my method has worked fine for me.
